### ISSUE TITLE
Some pop up menus are not displayed correctly (unreadable)

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/quietfox#1]
Some right click pop up menus (i.e. History, Notifications menu, Download, etc...) are not correctly displayed. They have a blank background and this results in getting an unreadable text, because we are assuming text is displayed in Nord Polar Dark.

If we knew the name of those classes it would be way easier

**Comment by mfarina122** [comment]
for now i've just changed menu pop ups characters colours from white to black into the history sidebar and bookmarks sidebar but this is only a temporary fix

**Comment by themoonmeetsthesun** [comment]
> Some right click pop up menus (i.e. History, Notifications menu, Download, etc...) are not correctly displayed. They have a blank background and this results in getting an unreadable text, because we are assuming text is displayed in Nord Polar Dark.
> 
> If we knew the name of those classes it would be way easier

It's in beta

**Comment by themoonmeetsthesun** [comment]
I also have a fork and it is in beta too lol

**Comment by TheGITofTeo997** [comment]
> > Some right click pop up menus (i.e. History, Notifications menu, Download, etc...) are not correctly displayed. They have a blank background and this results in getting an unreadable text, because we are assuming text is displayed in Nord Polar Dark.
> 
> > 
> 
> > If we knew the name of those classes it would be way easier
> 
> 
> 
> It's in beta

Did you realize that i am the author of this repo and issue did you?

**Comment by yurikodesu** [comment]
> > > Some right click pop up menus (i.e. History, Notifications menu, Download, etc...) are not correctly displayed. They have a blank background and this results in getting an unreadable text, because we are assuming text is displayed in Nord Polar Dark.
> > 
> > 
> > > 
> > 
> > 
> > > If we knew the name of those classes it would be way easier
> > 
> > 
> > It's in beta
> 
> Did you realize that i am the author of this repo and issue did you?

Wait I didn't see that 😅
Sorry?

**Comment by TheGITofTeo997** [comment]
> > > > Some right click pop up menus (i.e. History, Notifications menu, Download, etc...) are not correctly displayed. They have a blank background and this results in getting an unreadable text, because we are assuming text is displayed in Nord Polar Dark.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > If we knew the name of those classes it would be way easier
> 
> > > 
> 
> > > 
> 
> > > It's in beta
> 
> > 
> 
> > Did you realize that i am the author of this repo and issue did you?
> 
> 
> 
> Wait I didn't see that 😅
> 
> Sorry?

That's fine, no worries ✌️

**Comment by TheGITofTeo997** [comment]
We can consider this closed (even if not totally) with the latest push
