### ISSUE TITLE
Same code bloc ? why ?

### ISSUE THREAD

**Issue by GrosBourrin** [TheGITofTeo997/quietfox#4]
![](https://user-images.githubusercontent.com/40931468/208837133-df40000d-87ab-4442-9491-0287e1471995.jpg)

**Comment by mfarina122** [comment]
Thanks for letting me know. I've eliminated that part (it was useless after all) and now it should be gone.

**Comment by TheGITofTeo997** [comment]
@GrosBourrin This has been fixed with some code cleaning in 33a8bea, thanks for reporting
