### ISSUE TITLE
Adaptative Tab Bar Colour compatibility

### ISSUE THREAD

**Issue by khannurien** [TheGITofTeo997/quietfox#6]
Hi, thanks for the great theme!

It seems it is not compatible with the following extension: https://addons.mozilla.org/fr/firefox/addon/adaptive-tab-bar-colour/
When opened, the URL bar menu is transparent, making it hard to distinguish its content over the page content.

The extension author states that:

> A CSS theme can work with ATBC, when system colour variables are being used. 

They give a [theme example](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS) that works with ATBC.

If you have time to look into it, that would be great, but I opened this big report mostly to track the issue.

Thanks again!

**Comment by TheGITofTeo997** [comment]
Thanks for the report, maybe @mfarina122 could have a look at this

**Comment by TheGITofTeo997** [comment]
@khannurien 
Hello, can you test [43e023a](https://github.com/TheGITofTeo997/quietfoxReborn/commit/43e023a0396f2267e8df64f7a8d6aaf516c267ec) and report back please?
Thanks

**Comment by TheGITofTeo997** [comment]
Initial support added in the [latest release](https://github.com/TheGITofTeo997/quietfoxReborn/releases/download/v131/Quietfox_131.zip)
